### ISSUE TITLE
Spotifree generates several system.log messages per second in Yosemite

### ISSUE THREAD

**Issue by swrobel** [ArtemGordinsky/Spotifree#32]
Running Yosemite DP6 and seeing my system logs filled with this exact message as long as Spotifree is open and **Spotify is playing a song**:

`8/20/14 4:03:42.271 PM Spotifree[1087]: AppleEvents: Send port for process has no send right, port=( port:28651/0x6feb rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread`

I realize Yosemite is pre-release, but just wanted to give a heads-up on the potential issue.

**Comment by JrCs** [comment]
Do you have a fix ?

**Comment by E-n-e-a-s** [comment]
Apple... Please do your work. Impossible for us to fix.

**Comment by pmiddlet72** [comment]
Happening in 1.6.3. Not sure how much of a resource this actually takes up. Essentially it's telling me that the port it wishes to send on (10523/0x291b in this case) doesn't have permissions for sends. Which reminds me, here's a little relevant [gem].(https://developer.apple.com/library/mac/documentation/Security/Conceptual/AuthenticationAndAuthorizationGuide/Permissions/Permissions.html)

**Comment by vachooho** [comment]
I have similar warning logged each time I do send AS event using ScriptingBridge- in my case there is no impact on functionality - only excessive logging. I reported this to Apple some time ago, and today I got in my bug report "fixed in OS X 10.11". No explanation for the fix and no indication if it would be fixed in 10.10 - and I don't see that message logged in El Capitano preview.

**Comment by ArtemGordinsky** [comment]
@vachooho Thanks for letting us know! Glad to hear they finally fixed this.

**Comment by jdelisle** [comment]
On Yosemite, use the Console's Ignore Sender option on that log message to mitigate the issue. Keeps your logs clean :)
