### ISSUE TITLE
Visual Ads / Audio quality

### ISSUE THREAD

**Issue by ghost** [ArtemGordinsky/Spotifree#34]
Hey!

First at all... terryfic app you got there, it's the best that I've tried. OTOH I know how to disable Visual Ads and enable the High Quality Streaming... I think those would be a good addition for the app. Please let me know if you're interested.

Regards.

**Comment by nos1609** [comment]
Hi! Tested this bash script during a week
`echo "audio.play_bitrate=320000" >> /Users/nos1609/Library/Application\ Support/Spotify/prefs`
It works, but resets once spotify exits, probably gets overwritten.
Is there a possiility to automate this within your app?

**Comment by lordhellraiser** [comment]
If you have hombrew (you should), install `watch` and `gnu-sed` (with `--with-default-names` flag) then instead of appending the same text over and over just replace the value every XXX seconds:

`watch -n XXX sed -r 's/^(audio.play_bitrate).*/\1=320000/' -i /Users/nos1609/Library/Application\ Support/Spotify/prefs`

Hope it helps but YMMV, try and play a little with that... (I ditched Spotify for Apple Music.)
