### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by xxdavid** [ArtemGordinsky/Spotifree#71]
Why are you developing this app? You have a MacBook and don't have few bucks a month for unlimited music? If you don't, you have to listen to the ads – that's how it works. Or if you hate ads and don't want to pay for it, don't use Spotify at all. But this automatic muting is stealing or at least unethical, don't you think?
Maybe the time you invested into the development (150 commits isn't few) you could use to make some money to remove the ads (and get better quality, offline usage and better mobile support too).
Last think, have you even read EULA (I haven't), I think there can be something about this.

**Comment by EneasR** [comment]
> Why are you developing this app?

For experience. I just love to code and maintaining a real application helps you to get better. It is fun for me and I like to do it in my free time.
> You have a MacBook and don't have few bucks a month for unlimited music?

I personally do have a Spotify subscription but anyway, just because you are on a Mac OS does not imply that you have a lot of money. As a pupil or student maybe you have got a Mac from your parents. In Germany a subscription would cost converted 13,87US$ / month. That would be 166,44US$ a year. I do not think that this are "a few bucks" for those kind of poeple.

Furthermore there are many countries Spotify does not accept payments from. @ArtemGordinsky for example started to write his little AppleScript because this was the only way for him to experience Spotify without ads.
> This automatic muting is stealing or at least unethical, don't you think?

We are just muting the ads. The only one damaged are the companies which ads are played because we do not hear their ads but nevertheless they have to pay for it and personally I do not think this will hurt them. I could be wrong though. Please feel free to tell me if you think differently. Spotify or the Artists will get the same amount of money they would get if the ads were not muted.

>Maybe the time you invested into the development (150 commits isn't few) you could use to make some money to remove the ads

As I said, I love to invest time into development. It is fun to write code. Apart from this I do have a Spotify subscription...

I hope I could answer most of your questions. This just reflects my own opinion, so if you disagree or if there are any questions left open, feel free to comment.

**Comment by intenex** [comment]
Thanks for writing that response EneasR. Excellent, thoughtful, well reasoned reply. I'd just like to voice extreme gratitude and appreciation that you guys do provide this service. It's rare to see something as a niche open source project that's so well maintained, regularly updated, and that just works.

Cheers,
Ben

**Comment by xxdavid** [comment]
Sorry, "a few bucks" really was an exaggeration, especially for a student. But
it's still much better than buying every song you listen to.

I understand you a bit, I love development too. But imagine everyone would use
Spotifree, Spotify would has to cancel its free program, because no one would
like to advertise there.

Anyway, thank you for sharing your point of view.

On Tue, Jan 05, 2016 at 12:07 PM, Eneas < notifications@github.com [notifications@github.com] > wrote:
Why are you developing this app?

For experience. I just love to code and maintaining a real application helps you
to get better. It is fun for me and I like to do it in my free time.

You have a MacBook and don't have few bucks a month for unlimited music?

I personally do have a Spotify subscription but anyway, just because you are on
a Mac OS does not imply that you have a lot of money. As a pupil or student
maybe you have got a Mac from your parents. In Germany a subscription would cost
converted 13,87US$ / month. That would be 166,44US$ a year. I do not think that
this are "a few bucks" for those kind of poeple.

Furthermore there are many countries Spotify does not accept payments from. @ArtemGordinsky [https://github.com/ArtemGordinsky] for example started to write his little AppleScript because this was the only
way for him to experience Spotify without ads.

This automatic muting is stealing or at least unethical, don't you think?

We are just muting the ads. The only one damaged are the companies which ads are
played because we do not hear their ads but nevertheless they have to pay for it
and personally I do not think this will hurt them. I could be wrong though.
Please feel free to tell me if you think differently. Spotify or the Artists
will get the same amount of money they would get if the ads were not muted.

Maybe the time you invested into the development (150 commits isn't few) you
could use to make some money to remove the ads

As I said, I love to invest time into development. It is fun to write code.
Apart from this I do have a Spotify subscription...

I hope I could answer most of your questions. This just reflects my own opinion,
so if you disagree or if there are any questions left open, feel free to
comment.

—
Reply to this email directly or view it on GitHub
[https://github.com/ArtemGordinsky/Spotifree/issues/71#issuecomment-168973266] .[https://github.com/notifications/beacon/ADPHO7EBktbnQVHRXgexzB0NVd9kEUalks5pW5uFgaJpZM4G-Oj2.gif]

**Comment by EneasR** [comment]
>But imagine everyone would use Spotifree, Spotify would has to cancel its free program, because no one would like to advertise there.

You are right, but there is no need to imagine a scenario like this. According to this [source](https://press.spotify.com/nz/information) there are 75 million active Spotify users. Minus the 20 million subscribers, there are 55 million users with ads. Spotifree was downloaded about [50.000 times](http://spotifree.gordinskiy.com/about.html). These are just downloads but because I don't know how many of these are active users, I'll just use all of them. This would make 0,09% relevant Spotify users who are muting ads with Spotifree. I don't see any danger here.
Furthermore there are are video ads and popups, which are not blocked by Spotifree. Advertisers are still able to reach Spotifree users.

I think in the end, like it is with every other ad blocker, it is open for everyone to decide for himselft whether using it is acceptable or not. If you don't think it is, don't use it. It is just giving them an opportunity.

**Comment by xxdavid** [comment]
Yes, I agree it's everyone's choice.
